import React, { useState, useEffect } from 'react';
import net from '../../util/net';
import { useReportId } from '../framework/useReportId';

const CommentsReport = () => {
  const { report_id } = useReportId();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [topics, setTopics] = useState({});
  const [runs, setRuns] = useState({});
  const [selectedRunKey, setSelectedRunKey] = useState(null);

  useEffect(() => {
    if (!report_id) return;

    setLoading(true);
    // Fetch LLM topics from Delphi endpoint
    net.polisGet("/api/v3/delphi", {
      report_id: report_id
    })
      .then(response => {
        console.log("Delphi response:", response);
        
        if (response && response.status === "success") {
          if (response.runs && Object.keys(response.runs).length > 0) {
            // Set the runs data
            setRuns(response.runs);
            
            // Select the first (most recent) run by default
            const runKeys = Object.keys(response.runs);
            setSelectedRunKey(runKeys[0]);
          } else if (response.available_tables) {
            setError(`DynamoDB connected but the required table doesn't exist yet. This is normal until the Delphi pipeline has been run for this conversation.`);
          } else if (response.error) {
            setError(`Error: ${response.error}`);
          } else {
            setError("No LLM topic data available yet");
          }
        } else {
          setError("Failed to retrieve LLM topics");
        }
        
        setLoading(false);
      })
      .catch(err => {
        console.error("Error fetching LLM topics:", err);
        setError("Failed to connect to the Delphi endpoint");
        setLoading(false);
      });
  }, [report_id]);

  // Get the current selected run data
  const selectedRun = selectedRunKey ? runs[selectedRunKey] : null;

  // Render topic cards for a layer
  const renderTopicCards = (layerId) => {
    if (!selectedRun || !selectedRun.topics_by_layer || !selectedRun.topics_by_layer[layerId]) {
      return <p>No topics found for this layer</p>;
    }

    const layerTopics = selectedRun.topics_by_layer[layerId];
    return (
      <div className="topics-grid">
        {Object.keys(layerTopics).map(clusterId => {
          const topic = layerTopics[clusterId];
          // Skip topics that are clearly errors (like "Here are the topic labels:")
          if (topic.topic_name.toLowerCase().includes("here are the topic") || 
              topic.topic_name.toLowerCase().includes("topic label")) {
            return null;
          }
          
          return (
            <div key={`${layerId}-${clusterId}`} className="topic-card">
              <h3>{topic.topic_name}</h3>
              <p>Group {clusterId}</p>
              <p className="topic-meta">Generated by {topic.model_name} on {topic.created_at.substring(0, 10)}</p>
            </div>
          );
        })}
      </div>
    );
  };

  return (
    <div className="comments-report">
      {/* Use a simple h1 instead of the Heading component */}
      <div style={{
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        borderBottom: "1px solid #ccc",
        marginBottom: 20,
        paddingBottom: 10
      }}>
        <h1>Comments Report</h1>
        <div>Report ID: {report_id}</div>
      </div>

      {loading ? (
        <div className="loading">Loading LLM topics data...</div>
      ) : error ? (
        <div className="error-message">
          <h3>Not Available Yet</h3>
          <p>{error}</p>
          <p>
            The Delphi system needs to process this conversation with LLM topic generation 
            before this report will be available.
          </p>
        </div>
      ) : (
        <div className="topics-container">
          <div className="run-info">
            <div className="run-header">
              <h2>Group Topics <span style={{ fontWeight: 'normal', fontSize: '0.8em' }}>generated by {selectedRun?.model_name}</span></h2>
              <p className="generated-date">Generated on {selectedRun?.created_date}</p>
            </div>
            
            <p className="info-text">
              These are LLM-generated topic names based on the comments in each group.
              The algorithm has analyzed the content of comments to extract the main themes.
            </p>
            
            {selectedRun?.topics_by_layer && Object.keys(selectedRun.topics_by_layer).map(layerId => (
              <div key={layerId} className="layer-section">
                <h2>Group Themes</h2>
                {renderTopicCards(layerId)}
              </div>
            ))}
          </div>
        </div>
      )}

      <style jsx>{`
        .comments-report {
          padding: 20px;
          max-width: 1200px;
          margin: 0 auto;
        }
        
        .topics-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
          gap: 20px;
          margin-top: 20px;
        }
        
        .topic-card {
          border: 1px solid #e0e0e0;
          border-radius: 8px;
          padding: 16px;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
          background: white;
        }
        
        .topic-card h3 {
          margin-top: 0;
          color: #03a9f4;
        }
        
        .topic-meta {
          font-size: 0.8rem;
          color: #666;
          margin-top: 12px;
        }
        
        .layer-section {
          margin-top: 30px;
          padding-top: 20px;
          border-top: 1px solid #eee;
        }
        
        .run-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 5px;
        }
        
        .generated-date {
          color: #666;
          font-size: 0.9rem;
        }
        
        .info-text {
          background: #f0f7ff;
          padding: 15px;
          border-radius: 8px;
          margin-bottom: 30px;
          line-height: 1.5;
          color: #444;
          border-left: 4px solid #03a9f4;
        }
        
        .error-message {
          background: #fef8e8;
          border: 1px solid #f2d9a0;
          border-radius: 8px;
          padding: 20px;
          margin: 20px 0;
        }
        
        .loading {
          display: flex;
          justify-content: center;
          align-items: center;
          height: 200px;
          font-size: 18px;
          color: #666;
        }
      `}</style>
    </div>
  );
};

export default CommentsReport;