// Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

const s = {}

// Existing keys
s.share_but_no_comments_warning =
  "This conversation has no comments. We recommend you add a few comments before inviting participants. This will help participants get started. Go to 'Configure' and then 'Seed Comments'."
s.share_but_no_visible_comments_warning =
  'This conversation has no visible comments. We recommend you add a few comments (or moderate the comments that exist) before inviting participants, since this will help them understand what kind of comments they should submit.'
s.no_permission = 'Your account does not have the permissions to view this page.'

// ─── Navigation (nav_) ───
s.nav_polis = 'Polis'
s.nav_sign_out = 'sign out'
s.nav_conversations = 'Conversations'
s.nav_integrate = 'Integrate'
s.nav_account = 'Account'
s.nav_all = 'All'
s.nav_configure = 'Configure'
s.nav_distribute = 'Distribute'
s.nav_moderate = 'Moderate'
s.nav_monitor = 'Monitor'
s.nav_reports = 'Reports'
s.nav_invite_tree = 'Invite Tree'
s.nav_invite_codes = 'Invite Codes'
s.nav_participants = 'Participants'
s.nav_import = 'Import'

// ─── Config (config_) ───
s.config_heading = 'Configure'
s.config_saving = 'Saving'
s.config_up_to_date = 'Up to date'
s.config_error_saving = 'Error Saving'
s.config_is_active_label = 'Conversation Is Open'
s.config_is_active_desc = 'Conversation is open. Unchecking disables both voting and commenting.'
s.config_topic = 'Topic'
s.config_description = 'Description'
s.config_seed_comments = 'Seed Comments'
s.config_customize_ui = 'Customize the user interface'
s.config_vis_label = 'Visualization'
s.config_vis_desc = 'Participants can see the visualization'
s.config_write_label = 'Comment form'
s.config_write_desc = 'Participants can submit comments'
s.config_help_label = 'Help text'
s.config_help_desc = 'Show explanation text above voting and visualization'
s.config_subscribe_label = 'Prompt participants to subscribe to updates'
s.config_subscribe_desc =
  'Prompt participants to subscribe to updates. A prompt is shown to users once they finish voting on all available comments. If enabled, participants may optionally provide their email address to receive notifications when there are new comments to vote on.'
s.config_strict_mod_desc = 'No comments shown without moderator approval'
s.config_treevite_label = 'Enable Invite Tree'
s.config_treevite_desc =
  '[EXPERIMENTAL FEATURE] Enable Invite Tree. Nobody can participate without an invite. Invites are managed in waves.'
s.config_importance_label = 'Importance Enabled'
s.config_importance_desc =
  '[EXPERIMENTAL FEATURE] Participants can see the "This comment is important" checkbox'

// ─── Moderation (mod_) ───
s.mod_heading = 'Moderate'
s.mod_unmoderated = 'Unmoderated'
s.mod_accepted = 'Accepted'
s.mod_rejected = 'Rejected'
s.mod_loading_unmoderated = 'Loading unmoderated comments...'
s.mod_loading_accepted = 'Loading accepted comments...'
s.mod_loading_rejected = 'Loading rejected comments...'
s.mod_accept = 'accept'
s.mod_reject = 'reject'
s.mod_flag_warning =
  'Comment flagged by Polis Auto Moderator API. Comment not shown to participants. Accept to override.'
s.mod_metadata = 'metadata'

// ─── Seed Comments (seed_) ───
s.seed_submit = 'Submit'
s.seed_success = 'Success!'
s.seed_saving = 'Saving...'
s.seed_add = 'Add'
s.seed_link_text = 'seed comments or bulk upload as csv'
s.seed_for_participants = 'for participants to vote on:'
s.seed_upload_csv_heading = 'Upload a CSV of seed comments'
s.seed_csv_format = 'CSV Format:'
s.seed_original_id_note = 'original_id MUST be a UUID.'

// ─── Stats / Monitor (stats_) ───
s.stats_heading = 'Monitor'
s.stats_loading = 'Loading...'
s.stats_participants_voted = 'participants voted'
s.stats_votes_cast = 'votes were cast'
s.stats_votes_per_participant = 'votes per participant on average'
s.stats_commented = 'commented'
s.stats_comments_submitted = 'comments submitted'
s.stats_voters_over_time = 'Voters over time, by time of first vote'
s.stats_commenters_over_time = 'Commenters over time, by time of first comment'

// ─── Distribute / Share (dist_) ───
s.dist_heading = 'Distribute'
s.dist_share = 'Share'
s.dist_embed = 'Embed'
s.dist_embedded_on = 'Embedded on: '
s.dist_embed_note = 'This embed code can only be used to embed a single conversation.'
s.dist_integrate_link = 'I want to integrate pol.is on my entire site.'
s.dist_loading_comments = 'Loading accepted comments...'

// ─── Reports (reports_) ───
s.reports_heading = 'Reports'
s.reports_loading = 'Loading Reports...'
s.reports_select_comments = 'Select which comments will be visible in this report:'
s.reports_include_all = 'Include all comments'
s.reports_include_no_rejected = 'Include all comments except for moderation rejections'
s.reports_include_accepted_only = 'Include only moderator accepted comments'
s.reports_create = 'Create report url'
s.reports_modified = 'Modified'
s.reports_report_id = 'Report ID:'
s.reports_mod_level_0 = 'Showing only moderated comments'
s.reports_mod_level_minus1 = 'Showing moderated and unmoderated comments'
s.reports_mod_level_minus2 = 'Showing all comments, including those moderated out'
s.reports_urls = 'Report URLs'
s.reports_standard = 'Standard Report'
s.reports_data_export = 'Data Export'
s.reports_topic = 'Topic'
s.reports_topics_viz = 'Topics Viz'
s.reports_topic_stats = 'Topic Stats'
s.reports_topic_map_narrative = 'Topic Map Narrative'
s.reports_analysis_insights = 'Analysis & Insights'
s.reports_delphi_promo = 'Discover more with Delphi - advanced data analysis and AI'
s.reports_minutes_ago = '{{count}} minutes ago'
s.reports_hours_ago = '{{count}} hours ago'
s.reports_days_ago = '{{count}} days ago'

// ─── Conversations (convos_) ───
s.convos_heading = 'All Conversations'
s.convos_my = 'My Conversations'
s.convos_all = 'All Conversations'
s.convos_create_new = 'Create new conversation'
s.convos_loading = 'Loading conversations...'
s.convos_error = 'Error loading conversations'
s.convos_owner_email_placeholder = 'Owner email contains...'
s.convos_all_statuses = 'All statuses'
s.convos_active = 'Active'
s.convos_inactive = 'Inactive'
s.convos_min_comments = 'Min comments'
s.convos_min_participants = 'Min participants'
s.convos_updated_days = 'Updated in last N days'
s.convos_created_days = 'Created in last N days'
s.convos_sort_updated = 'Sort: Updated'
s.convos_sort_created = 'Sort: Created'
s.convos_sort_participants = 'Sort: Participants'
s.convos_sort_comments = 'Sort: Comments'
s.convos_desc = 'Desc'
s.convos_asc = 'Asc'
s.convos_apply = 'Apply'
s.convos_col_topic = 'Topic'
s.convos_col_participants = 'Participants'
s.convos_col_comments = 'Comments'
s.convos_col_updated = 'Updated'
s.convos_col_created = 'Created'
s.convos_col_owner_email = 'Owner Email'
s.convos_col_active = 'Active'
s.convos_label_topic = 'Topic: '
s.convos_label_participants = 'Participants: '
s.convos_label_comments = 'Comments: '
s.convos_label_updated = 'Updated: '
s.convos_label_created = 'Created: '
s.convos_label_owner = 'Owner: '
s.convos_label_active = 'Active: '
s.convos_embedded_on = 'Embedded on {{url}}'
s.convos_participants_count = '{{count}} participants'
// Interstitial
s.convos_interstitial_heading = 'Introducing Polis 2: AI-Powered Insights'
s.convos_interstitial_desc =
  'Unlock deeper understanding from your conversations with Polis 2, our advanced analytics, moderation, and AI reporting suite.'
s.convos_interstitial_analysis = 'Advanced Statistical Analysis'
s.convos_interstitial_analysis_desc =
  'Go beyond opinion groups with interactive topic maps and advanced data visualizations. See how ideas connect and identify key areas of contention and consensus.'
s.convos_interstitial_reports = 'AI-Generated Reports'
s.convos_interstitial_reports_desc =
  'Let Polis 2 do the heavy lifting. Get AI-generated summaries, consensus statements, and detailed reports on conversation dynamics and key topics.'
s.convos_interstitial_features = 'Key Polis 2 Features:'
s.convos_interstitial_feature_1 = 'Conversation Summaries'
s.convos_interstitial_feature_2 = 'Automated Topic Reporting'
s.convos_interstitial_feature_3 = 'Identification of Consensus Statements'
s.convos_interstitial_feature_4 = 'Divisive Comment Analysis'
s.convos_interstitial_ready = 'Ready to supercharge your analysis?'
s.convos_interstitial_upgrade = 'Upgrade to a Pro plan to access Polis 2.'
s.convos_interstitial_later = 'Maybe Later'
s.convos_interstitial_create = 'Create Conversation'

// ─── Invite Tree (invite_) ───
s.invite_tree_heading = 'Invite Tree'
s.invite_tree_not_enabled =
  'Invite Tree is not enabled. To use this feature, enable Invite Tree in the Conversation Configure options.'
s.invite_tree_invite_only =
  'This conversation is invite only. Participants must enter a valid invite code to vote or comment.'
s.invite_waves_heading = 'Waves'
s.invite_wave_info = 'Wave {{wave}} (parent {{parent}}) — ipu {{ipu}}, owner {{owner}}, size {{size}}'
s.invite_no_waves = 'No waves yet. Create the initial wave below.'
s.invite_create_next_wave = 'Create Next Wave'
s.invite_invites_per_user = 'Invites per user (granted to each participant in the parent wave)'
s.invite_owner_invites = 'Owner invites (additional invites for you to distribute this wave)'
s.invite_parent_wave_desc =
  'Parent wave (optional override). Default is latest existing wave; use 0 for root.'
s.invite_latest_default = 'Latest (default)'
s.invite_root = 'Root (0)'
s.invite_wave_n = 'Wave {{wave}}'
s.invite_creating = 'Creating…'
s.invite_create_wave = 'Create Wave'
s.invite_created_summary = 'Created wave {{wave}}. Invites created: {{count}}'
s.invite_codes_heading = 'Invite Codes'
s.invite_codes_desc = 'These are the invite codes for the owner of this conversation.'
s.invite_preparing = 'Preparing…'
s.invite_download_csv = 'Download CSV'
s.invite_filters = 'Filters'
s.invite_filter_wave = 'Wave'
s.invite_filter_status = 'Status'
s.invite_all_waves = 'All waves'
s.invite_all_statuses = 'All statuses'
s.invite_status_unused = 'Unused'
s.invite_status_used = 'Used'
s.invite_status_revoked = 'Revoked'
s.invite_status_expired = 'Expired'
s.invite_status_n = 'Status {{status}}'
s.invite_clear_filters = 'Clear Filters'
s.invite_found_codes = 'Found {{count}} invite codes:'
s.invite_col_code = 'Code'
s.invite_col_wave = 'Wave'
s.invite_col_status = 'Status'
s.invite_col_used_at = 'Used At'
s.invite_na = 'N/A'
s.invite_no_codes =
  'No invite codes found. Create waves in the Invite Tree section to generate codes.'

// ─── Participants (participants_) ───
s.participants_heading = 'Participant Management'
s.participants_manage = 'Manage participants for conversation {{id}}.'
s.participants_xid_required = 'XID Required to Vote'
s.participants_xid_required_note = 'Required because XID Allow List is enabled.'
s.participants_use_allow_list = 'Use XID Allow List'
s.participants_tab_in_use = 'XIDs in Use'
s.participants_tab_allowed = 'XIDs Allowed'
s.participants_no_xids = 'No XIDs found for this conversation.'
s.participants_preparing = 'Preparing…'
s.participants_download_csv = 'Download CSV'
s.participants_col_pid = 'PID'
s.participants_col_xid = 'XID'
s.participants_col_votes = 'Votes'
s.participants_upload_xids = 'Upload XIDs'
s.participants_no_allow_list = 'No XIDs in the allow list for this conversation.'
s.participants_upload_heading = 'Upload XIDs'
s.participants_upload_desc =
  'Upload a file or paste a list of XIDs to allow. Supports CSV files (with or without headers) and plain text files (one XID per line).'
s.participants_processing = 'Processing file...'
s.participants_drop_here = 'Drop file here'
s.participants_browse_or_drop = 'Click to browse or drag and drop file here'
s.participants_supports_csv = 'Supports CSV and text files'
s.participants_allowed_xids = 'Allowed XIDs'
s.participants_paste_placeholder = 'Paste XIDs here, one per line, or upload a file above'
s.participants_replace_all = 'Replace all existing XIDs'
s.participants_cancel = 'Cancel'

// ─── Import / BYOD (import_) ───
s.import_heading = 'Import'
s.import_success =
  'Your import was successful. You will receive an email once the job is completed.'
s.import_desc =
  'Import external conversation data (comments and votes) from external sources for reporting metrics. This function requires uploading two CSV files, one containing comments, and another containing votes. Comment upload must occur first. After a successful import job, you will recieve an email notifying you that the data is ready.'
s.import_comments_heading = 'Import Comments'
s.import_votes_heading =
  'Upload a CSV of votes. comment_id field MUST match original_id field in comments csv. Size limit 50MB'
s.import_votes_note = 'vote_value MUST follow the pattern: 1 = agree, -1 = disagree, 0 = neutral/pass'
s.import_upload_votes = 'Upload Votes'

// ─── Pagination (pagination_) ───
s.pagination_showing = 'Showing {{start}}-{{end}} of {{total}} items'
s.pagination_first = 'First'
s.pagination_previous = 'Previous'
s.pagination_page = 'Page {{current}} of {{totalPages}}'
s.pagination_next = 'Next'
s.pagination_last = 'Last'

// ─── Account (account_) ───
s.account_heading = 'Account'
s.account_greeting = 'Hi {{name}}!'

// ─── Auth (auth_) ───
s.auth_sign_in = 'Sign In'
s.auth_signing_out = 'Signing out...'
s.auth_signout_error = 'Signout error: {{error}}'
s.auth_redirecting = 'Redirecting to home page...'

// ─── Topic Moderation (topic_) ───
s.topic_heading = 'Topic Moderation'
s.topic_topics_tree = 'Topics Tree'
s.topic_proximity_map = 'Proximity Map'
s.topic_statistics = 'Statistics'
s.topic_not_enabled = 'Topic moderation is not enabled for this conversation.'
s.topic_pro_feature = 'This is a Pro feature. See pro.pol.is for more information.'
s.topic_loading = 'Loading...'
s.topic_loading_topics = 'Loading topics...'
s.topic_loading_comments = 'Loading comments...'
s.topic_loading_statistics = 'Loading statistics...'
s.topic_error = 'Error: {{error}}'
s.topic_retry = 'Retry'
s.topic_no_topics = 'No topics available for this conversation.'
s.topic_no_topics_hint =
  'Topics are generated by the Delphi pipeline. Make sure the pipeline has been run for this conversation.'
s.topic_view_layer = 'View Layer:'
s.topic_layer = 'Layer {{id}}'
s.topic_all_layers = 'All Layers'
s.topic_layer_count = 'Layer {{id}} ({{count}} topics)'
s.topic_cluster = 'Cluster {{id}}'
s.topic_status_label = 'Status: {{status}}'
s.topic_unnamed = 'Unnamed Topic'
s.topic_n_comments = '{{count}} comments'
s.topic_no_comments = 'No comments'
s.topic_accept = 'Accept'
s.topic_reject = 'Reject'
s.topic_view_comments = 'View Comments'
s.topic_model = 'Model: {{model}}'
s.topic_unknown = 'Unknown'
s.topic_created_at = 'Created: {{date}}'
s.topic_moderated_by = 'Moderated by: {{moderator}}'
s.topic_back_to_topics = '← Back to Topics'
s.topic_topic_label = 'Topic: {{key}}'
s.topic_comment_count = '{{count}} comments'
s.topic_select_all = 'Select All ({{count}} selected)'
s.topic_accept_selected = 'Accept Selected'
s.topic_reject_selected = 'Reject Selected'
s.topic_no_comments_for_topic = 'No comments found for this topic.'
s.topic_comment_id = 'ID: {{id}}'
s.topic_comment_cluster = 'Cluster: {{id}}'
s.topic_comment_layer = 'Layer: {{id}}'
s.topic_comment_position = 'Position: ({{x}}, {{y}})'
s.topic_status_accepted = 'Accepted'
s.topic_status_rejected = 'Rejected'
s.topic_status_meta = 'Meta'
s.topic_status_pending = 'Pending'
s.topic_stats_heading = 'Topic Moderation Statistics'
s.topic_stats_total = 'Total Topics'
s.topic_stats_pending = 'Pending'
s.topic_stats_accepted = 'Accepted'
s.topic_stats_rejected = 'Rejected'
s.topic_stats_completion = 'Completion Rate'
s.topic_stats_progress_heading = 'Moderation Progress'
s.topic_stats_overall = 'Overall Progress'
s.topic_stats_complete = '{{rate}}% Complete'
s.topic_stats_accepted_count = 'Accepted: {{count}}'
s.topic_stats_rejected_count = 'Rejected: {{count}}'
s.topic_stats_pending_count = 'Pending: {{count}}'
s.topic_stats_no_topics = 'No topics have been generated for this conversation yet.'
s.topic_stats_run_pipeline = 'Run the Delphi pipeline to generate topics for moderation.'
s.topic_stats_no_data = 'No statistics available.'
s.topic_network_error_topics = 'Network error loading topics'
s.topic_network_error_comments = 'Network error loading comments'
s.topic_network_error_statistics = 'Network error loading statistics'

export default s
