// Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

const s = {}

// Existing keys
s.share_but_no_comments_warning =
  "이 대화에는 의견이 없습니다. 참여자를 초대하기 전에 몇 가지 의견을 추가하는 것을 권장합니다. 이렇게 하면 참여자들이 시작하는 데 도움이 됩니다. '설정'으로 이동한 다음 '시드 의견'을 선택하세요."
s.share_but_no_visible_comments_warning =
  '이 대화에는 표시되는 의견이 없습니다. 참여자를 초대하기 전에 몇 가지 의견을 추가하거나 기존 의견을 검토하는 것을 권장합니다. 이렇게 하면 참여자들이 어떤 종류의 의견을 제출해야 하는지 이해하는 데 도움이 됩니다.'
s.no_permission = '이 페이지를 볼 수 있는 권한이 없습니다.'

// ─── Navigation (nav_) ───
s.nav_polis = 'Polis'
s.nav_sign_out = '로그아웃'
s.nav_conversations = '대화'
s.nav_integrate = '연동'
s.nav_account = '계정'
s.nav_all = '전체'
s.nav_configure = '설정'
s.nav_distribute = '배포'
s.nav_moderate = '검토'
s.nav_monitor = '모니터'
s.nav_reports = '보고서'
s.nav_invite_tree = '초대 트리'
s.nav_invite_codes = '초대 코드'
s.nav_participants = '참여자'
s.nav_import = '가져오기'

// ─── Config (config_) ───
s.config_heading = '설정'
s.config_saving = '저장 중'
s.config_up_to_date = '최신 상태'
s.config_error_saving = '저장 오류'
s.config_is_active_label = '대화 열림'
s.config_is_active_desc = '대화가 열려 있습니다. 체크를 해제하면 투표와 의견 작성이 모두 비활성화됩니다.'
s.config_topic = '주제'
s.config_description = '설명'
s.config_seed_comments = '시드 의견'
s.config_customize_ui = '사용자 인터페이스 커스터마이즈'
s.config_vis_label = '시각화'
s.config_vis_desc = '참여자가 시각화를 볼 수 있습니다'
s.config_write_label = '의견 작성 폼'
s.config_write_desc = '참여자가 의견을 제출할 수 있습니다'
s.config_help_label = '도움말 텍스트'
s.config_help_desc = '투표 및 시각화 위에 설명 텍스트 표시'
s.config_subscribe_label = '참여자에게 업데이트 구독 요청'
s.config_subscribe_desc =
  '참여자에게 업데이트 구독을 요청합니다. 사용 가능한 모든 의견에 투표를 마치면 안내가 표시됩니다. 활성화하면 참여자가 새로운 의견이 있을 때 알림을 받기 위해 이메일 주소를 선택적으로 제공할 수 있습니다.'
s.config_strict_mod_desc = '검토자 승인 없이는 의견이 표시되지 않음'
s.config_treevite_label = '초대 트리 활성화'
s.config_treevite_desc =
  '[실험적 기능] 초대 트리를 활성화합니다. 초대 없이는 아무도 참여할 수 없습니다. 초대는 웨이브 단위로 관리됩니다.'
s.config_importance_label = '중요도 활성화'
s.config_importance_desc =
  '[실험적 기능] 참여자가 "이 의견은 중요합니다" 체크박스를 볼 수 있습니다'

// ─── Moderation (mod_) ───
s.mod_heading = '검토'
s.mod_unmoderated = '미검토'
s.mod_accepted = '승인됨'
s.mod_rejected = '거부됨'
s.mod_loading_unmoderated = '미검토 의견을 불러오는 중...'
s.mod_loading_accepted = '승인된 의견을 불러오는 중...'
s.mod_loading_rejected = '거부된 의견을 불러오는 중...'
s.mod_accept = '승인'
s.mod_reject = '거부'
s.mod_flag_warning =
  'Polis 자동 검토 API에 의해 플래그된 의견입니다. 참여자에게 표시되지 않습니다. 승인하여 재정의하세요.'
s.mod_metadata = '메타데이터'

// ─── Seed Comments (seed_) ───
s.seed_submit = '제출'
s.seed_success = '성공!'
s.seed_saving = '저장 중...'
s.seed_add = '추가'
s.seed_link_text = '시드 의견 또는 CSV 일괄 업로드'
s.seed_for_participants = '참여자 투표용:'
s.seed_upload_csv_heading = '시드 의견 CSV 업로드'
s.seed_csv_format = 'CSV 형식:'
s.seed_original_id_note = 'original_id는 반드시 UUID여야 합니다.'

// ─── Stats / Monitor (stats_) ───
s.stats_heading = '모니터'
s.stats_loading = '불러오는 중...'
s.stats_participants_voted = '명이 투표함'
s.stats_votes_cast = '표가 투표됨'
s.stats_votes_per_participant = '참여자당 평균 투표 수'
s.stats_commented = '명이 의견 작성'
s.stats_comments_submitted = '개 의견 제출됨'
s.stats_voters_over_time = '시간별 투표자 수 (첫 투표 기준)'
s.stats_commenters_over_time = '시간별 의견 작성자 수 (첫 의견 기준)'

// ─── Distribute / Share (dist_) ───
s.dist_heading = '배포'
s.dist_share = '공유'
s.dist_embed = '임베드'
s.dist_embedded_on = '임베드 위치: '
s.dist_embed_note = '이 임베드 코드는 단일 대화에만 사용할 수 있습니다.'
s.dist_integrate_link = '전체 사이트에 pol.is를 연동하고 싶습니다.'
s.dist_loading_comments = '승인된 의견을 불러오는 중...'

// ─── Reports (reports_) ───
s.reports_heading = '보고서'
s.reports_loading = '보고서 불러오는 중...'
s.reports_select_comments = '이 보고서에 표시할 의견을 선택하세요:'
s.reports_include_all = '모든 의견 포함'
s.reports_include_no_rejected = '검토 거부된 의견을 제외한 모든 의견 포함'
s.reports_include_accepted_only = '검토자가 승인한 의견만 포함'
s.reports_create = '보고서 URL 생성'
s.reports_modified = '수정됨'
s.reports_report_id = '보고서 ID:'
s.reports_mod_level_0 = '검토된 의견만 표시'
s.reports_mod_level_minus1 = '검토된 의견과 미검토 의견 표시'
s.reports_mod_level_minus2 = '검토 거부된 의견을 포함한 모든 의견 표시'
s.reports_urls = '보고서 URL'
s.reports_standard = '표준 보고서'
s.reports_data_export = '데이터 내보내기'
s.reports_topic = '토픽'
s.reports_topics_viz = '토픽 시각화'
s.reports_topic_stats = '토픽 통계'
s.reports_topic_map_narrative = '토픽 맵 내러티브'
s.reports_analysis_insights = '분석 및 인사이트'
s.reports_delphi_promo = 'Delphi로 더 알아보기 - 고급 데이터 분석 및 AI'
s.reports_minutes_ago = '{{count}}분 전'
s.reports_hours_ago = '{{count}}시간 전'
s.reports_days_ago = '{{count}}일 전'

// ─── Conversations (convos_) ───
s.convos_heading = '모든 대화'
s.convos_my = '내 대화'
s.convos_all = '모든 대화'
s.convos_create_new = '새 대화 만들기'
s.convos_loading = '대화를 불러오는 중...'
s.convos_error = '대화 불러오기 오류'
s.convos_owner_email_placeholder = '소유자 이메일 포함...'
s.convos_all_statuses = '모든 상태'
s.convos_active = '활성'
s.convos_inactive = '비활성'
s.convos_min_comments = '최소 의견 수'
s.convos_min_participants = '최소 참여자 수'
s.convos_updated_days = '최근 N일 내 업데이트'
s.convos_created_days = '최근 N일 내 생성'
s.convos_sort_updated = '정렬: 업데이트순'
s.convos_sort_created = '정렬: 생성순'
s.convos_sort_participants = '정렬: 참여자순'
s.convos_sort_comments = '정렬: 의견순'
s.convos_desc = '내림차순'
s.convos_asc = '오름차순'
s.convos_apply = '적용'
s.convos_col_topic = '주제'
s.convos_col_participants = '참여자'
s.convos_col_comments = '의견'
s.convos_col_updated = '업데이트'
s.convos_col_created = '생성일'
s.convos_col_owner_email = '소유자 이메일'
s.convos_col_active = '활성'
s.convos_label_topic = '주제: '
s.convos_label_participants = '참여자: '
s.convos_label_comments = '의견: '
s.convos_label_updated = '업데이트: '
s.convos_label_created = '생성일: '
s.convos_label_owner = '소유자: '
s.convos_label_active = '활성: '
s.convos_embedded_on = '{{url}}에 임베드됨'
s.convos_participants_count = '참여자 {{count}}명'
// Interstitial
s.convos_interstitial_heading = 'Polis 2 소개: AI 기반 인사이트'
s.convos_interstitial_desc =
  'Polis 2의 고급 분석, 검토 및 AI 보고 기능으로 대화에서 더 깊은 이해를 얻으세요.'
s.convos_interstitial_analysis = '고급 통계 분석'
s.convos_interstitial_analysis_desc =
  '인터랙티브 토픽 맵과 고급 데이터 시각화로 의견 그룹을 넘어서세요. 아이디어가 어떻게 연결되는지 확인하고 주요 논쟁점과 합의점을 파악하세요.'
s.convos_interstitial_reports = 'AI 생성 보고서'
s.convos_interstitial_reports_desc =
  'Polis 2가 무거운 작업을 대신합니다. AI가 생성한 요약, 합의 진술, 대화 역학 및 주요 토픽에 대한 상세 보고서를 받으세요.'
s.convos_interstitial_features = 'Polis 2 주요 기능:'
s.convos_interstitial_feature_1 = '대화 요약'
s.convos_interstitial_feature_2 = '자동 토픽 보고'
s.convos_interstitial_feature_3 = '합의 진술 식별'
s.convos_interstitial_feature_4 = '분열적 의견 분석'
s.convos_interstitial_ready = '분석을 강화할 준비가 되셨나요?'
s.convos_interstitial_upgrade = 'Pro 플랜으로 업그레이드하여 Polis 2에 접근하세요.'
s.convos_interstitial_later = '나중에'
s.convos_interstitial_create = '대화 만들기'

// ─── Invite Tree (invite_) ───
s.invite_tree_heading = '초대 트리'
s.invite_tree_not_enabled =
  '초대 트리가 활성화되지 않았습니다. 이 기능을 사용하려면 대화 설정 옵션에서 초대 트리를 활성화하세요.'
s.invite_tree_invite_only =
  '이 대화는 초대 전용입니다. 참여자는 유효한 초대 코드를 입력해야 투표하거나 의견을 작성할 수 있습니다.'
s.invite_waves_heading = '웨이브'
s.invite_wave_info = '웨이브 {{wave}} (상위 {{parent}}) — 사용자당 {{ipu}}개, 소유자 {{owner}}개, 규모 {{size}}'
s.invite_no_waves = '아직 웨이브가 없습니다. 아래에서 초기 웨이브를 생성하세요.'
s.invite_create_next_wave = '다음 웨이브 생성'
s.invite_invites_per_user = '사용자당 초대 수 (상위 웨이브의 각 참여자에게 부여)'
s.invite_owner_invites = '소유자 초대 수 (이 웨이브에서 배포할 추가 초대)'
s.invite_parent_wave_desc =
  '상위 웨이브 (선택적 재정의). 기본값은 최신 기존 웨이브이며, 루트는 0을 사용하세요.'
s.invite_latest_default = '최신 (기본값)'
s.invite_root = '루트 (0)'
s.invite_wave_n = '웨이브 {{wave}}'
s.invite_creating = '생성 중…'
s.invite_create_wave = '웨이브 생성'
s.invite_created_summary = '웨이브 {{wave}} 생성 완료. 생성된 초대: {{count}}개'
s.invite_codes_heading = '초대 코드'
s.invite_codes_desc = '이 대화 소유자의 초대 코드입니다.'
s.invite_preparing = '준비 중…'
s.invite_download_csv = 'CSV 다운로드'
s.invite_filters = '필터'
s.invite_filter_wave = '웨이브'
s.invite_filter_status = '상태'
s.invite_all_waves = '모든 웨이브'
s.invite_all_statuses = '모든 상태'
s.invite_status_unused = '미사용'
s.invite_status_used = '사용됨'
s.invite_status_revoked = '취소됨'
s.invite_status_expired = '만료됨'
s.invite_status_n = '상태 {{status}}'
s.invite_clear_filters = '필터 초기화'
s.invite_found_codes = '초대 코드 {{count}}개 발견:'
s.invite_col_code = '코드'
s.invite_col_wave = '웨이브'
s.invite_col_status = '상태'
s.invite_col_used_at = '사용 시간'
s.invite_na = 'N/A'
s.invite_no_codes = '초대 코드를 찾을 수 없습니다. 초대 트리 섹션에서 웨이브를 생성하여 코드를 만드세요.'

// ─── Participants (participants_) ───
s.participants_heading = '참여자 관리'
s.participants_manage = '대화 {{id}}의 참여자를 관리합니다.'
s.participants_xid_required = '투표에 XID 필수'
s.participants_xid_required_note = 'XID 허용 목록이 활성화되어 있어 필수입니다.'
s.participants_use_allow_list = 'XID 허용 목록 사용'
s.participants_tab_in_use = '사용 중인 XID'
s.participants_tab_allowed = '허용된 XID'
s.participants_no_xids = '이 대화에 대한 XID를 찾을 수 없습니다.'
s.participants_preparing = '준비 중…'
s.participants_download_csv = 'CSV 다운로드'
s.participants_col_pid = 'PID'
s.participants_col_xid = 'XID'
s.participants_col_votes = '투표'
s.participants_upload_xids = 'XID 업로드'
s.participants_no_allow_list = '이 대화의 허용 목록에 XID가 없습니다.'
s.participants_upload_heading = 'XID 업로드'
s.participants_upload_desc =
  '허용할 XID 파일을 업로드하거나 목록을 붙여넣으세요. 헤더 유무에 관계없이 CSV 파일과 일반 텍스트 파일(한 줄에 하나의 XID)을 지원합니다.'
s.participants_processing = '파일 처리 중...'
s.participants_drop_here = '여기에 파일을 놓으세요'
s.participants_browse_or_drop = '클릭하여 찾아보거나 여기에 파일을 끌어다 놓으세요'
s.participants_supports_csv = 'CSV 및 텍스트 파일 지원'
s.participants_allowed_xids = '허용된 XID'
s.participants_paste_placeholder = '여기에 XID를 붙여넣으세요 (한 줄에 하나씩), 또는 위에서 파일을 업로드하세요'
s.participants_replace_all = '기존 XID 모두 교체'
s.participants_cancel = '취소'

// ─── Import / BYOD (import_) ───
s.import_heading = '가져오기'
s.import_success = '가져오기가 성공했습니다. 작업이 완료되면 이메일을 받게 됩니다.'
s.import_desc =
  '외부 소스에서 보고 지표용 외부 대화 데이터(의견 및 투표)를 가져옵니다. 이 기능은 의견이 포함된 CSV 파일과 투표가 포함된 CSV 파일, 총 두 개의 CSV 파일 업로드가 필요합니다. 의견 업로드를 먼저 해야 합니다. 성공적인 가져오기 작업 후 데이터가 준비되었음을 알리는 이메일을 받게 됩니다.'
s.import_comments_heading = '의견 가져오기'
s.import_votes_heading =
  '투표 CSV 업로드. comment_id 필드는 반드시 의견 CSV의 original_id 필드와 일치해야 합니다. 크기 제한 50MB'
s.import_votes_note = 'vote_value는 반드시 다음 패턴을 따라야 합니다: 1 = 동의, -1 = 반대, 0 = 중립/패스'
s.import_upload_votes = '투표 업로드'

// ─── Pagination (pagination_) ───
s.pagination_showing = '{{start}}-{{end}} / {{total}}개 항목'
s.pagination_first = '처음'
s.pagination_previous = '이전'
s.pagination_page = '{{current}} / {{totalPages}} 페이지'
s.pagination_next = '다음'
s.pagination_last = '마지막'

// ─── Account (account_) ───
s.account_heading = '계정'
s.account_greeting = '안녕하세요 {{name}}님!'

// ─── Auth (auth_) ───
s.auth_sign_in = '로그인'
s.auth_signing_out = '로그아웃 중...'
s.auth_signout_error = '로그아웃 오류: {{error}}'
s.auth_redirecting = '홈 페이지로 이동 중...'

// ─── Topic Moderation (topic_) ───
s.topic_heading = '토픽 검토'
s.topic_topics_tree = '토픽 트리'
s.topic_proximity_map = '근접도 맵'
s.topic_statistics = '통계'
s.topic_not_enabled = '이 대화에서는 토픽 검토가 활성화되지 않았습니다.'
s.topic_pro_feature = 'Pro 기능입니다. 자세한 내용은 pro.pol.is를 참조하세요.'
s.topic_loading = '불러오는 중...'
s.topic_loading_topics = '토픽을 불러오는 중...'
s.topic_loading_comments = '의견을 불러오는 중...'
s.topic_loading_statistics = '통계를 불러오는 중...'
s.topic_error = '오류: {{error}}'
s.topic_retry = '재시도'
s.topic_no_topics = '이 대화에 사용 가능한 토픽이 없습니다.'
s.topic_no_topics_hint =
  '토픽은 Delphi 파이프라인에 의해 생성됩니다. 이 대화에 대해 파이프라인이 실행되었는지 확인하세요.'
s.topic_view_layer = '레이어 보기:'
s.topic_layer = '레이어 {{id}}'
s.topic_all_layers = '모든 레이어'
s.topic_layer_count = '레이어 {{id}} ({{count}}개 토픽)'
s.topic_cluster = '클러스터 {{id}}'
s.topic_status_label = '상태: {{status}}'
s.topic_unnamed = '이름 없는 토픽'
s.topic_n_comments = '{{count}}개 의견'
s.topic_no_comments = '의견 없음'
s.topic_accept = '승인'
s.topic_reject = '거부'
s.topic_view_comments = '의견 보기'
s.topic_model = '모델: {{model}}'
s.topic_unknown = '알 수 없음'
s.topic_created_at = '생성: {{date}}'
s.topic_moderated_by = '검토자: {{moderator}}'
s.topic_back_to_topics = '← 토픽으로 돌아가기'
s.topic_topic_label = '토픽: {{key}}'
s.topic_comment_count = '{{count}}개 의견'
s.topic_select_all = '전체 선택 ({{count}}개 선택됨)'
s.topic_accept_selected = '선택 항목 승인'
s.topic_reject_selected = '선택 항목 거부'
s.topic_no_comments_for_topic = '이 토픽에 대한 의견을 찾을 수 없습니다.'
s.topic_comment_id = 'ID: {{id}}'
s.topic_comment_cluster = '클러스터: {{id}}'
s.topic_comment_layer = '레이어: {{id}}'
s.topic_comment_position = '위치: ({{x}}, {{y}})'
s.topic_status_accepted = '승인됨'
s.topic_status_rejected = '거부됨'
s.topic_status_meta = '메타'
s.topic_status_pending = '대기 중'
s.topic_stats_heading = '토픽 검토 통계'
s.topic_stats_total = '전체 토픽'
s.topic_stats_pending = '대기 중'
s.topic_stats_accepted = '승인됨'
s.topic_stats_rejected = '거부됨'
s.topic_stats_completion = '완료율'
s.topic_stats_progress_heading = '검토 진행 상황'
s.topic_stats_overall = '전체 진행률'
s.topic_stats_complete = '{{rate}}% 완료'
s.topic_stats_accepted_count = '승인: {{count}}개'
s.topic_stats_rejected_count = '거부: {{count}}개'
s.topic_stats_pending_count = '대기: {{count}}개'
s.topic_stats_no_topics = '이 대화에 대해 아직 토픽이 생성되지 않았습니다.'
s.topic_stats_run_pipeline = '검토용 토픽을 생성하려면 Delphi 파이프라인을 실행하세요.'
s.topic_stats_no_data = '사용 가능한 통계가 없습니다.'
s.topic_network_error_topics = '토픽 로딩 네트워크 오류'
s.topic_network_error_comments = '의견 로딩 네트워크 오류'
s.topic_network_error_statistics = '통계 로딩 네트워크 오류'

export default s
