env:
  browser: true
  es2021: true
  jquery: true
extends:
  - eslint:recommended
  - plugin:react/recommended
globals:
  _: readonly
  d3: readonly
  process: readonly
ignorePatterns:
  - build
  - devel
  - dist
overrides:
  - files:
    - "*.js"
    excludedFiles:
    - "**/*.test.js"
    - "**/*/*.js"
    env:
      node: true
      browser: false
  - files:
    - "**/*.test.js"
    env:
      jest: true
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  react/prop-types: warn
settings:
  react:
    version: 'detect'
